version: '3.7'

services:
  nest:
    container_name: 'nest'
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MONGO_URI: '${CONNECT_STRING}'
    ports:
      - '4000:${PORT}'
      - 9229:9229
    command: npm run start
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - server-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env
    networks:
      - server-network
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ${DB_HOST}:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  server-network:

volumes:
  mongodb_data_container:
