version: '3.6'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
    networks:
      - server-network
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017

  nest:
    container_name: 'nest'
    build:
      context: .
      target: development
      # only will build dev stage from dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONNECT_STRING=${CONNECT_STRING}
      - PORT=${PORT}
      - NODE_ENV=production
    ports:
      - '4000:${PORT}'
      - 9229:9229
    restart: unless-stopped
    networks:
      - server-network
    depends_on:
      - mongodb

networks:
  server-network:

volumes:
  mongodata:
    driver: local
